### ISSUE TITLE
Make swiss-qr-bill ready for expansion

### ISSUE THREAD

**Issue by molitoris** [claudep/swiss-qr-bill#34]
I think swiss-qr-bill is a good project and see a lot of potential.

**Current situation**
Currently all functionality is combined in one module. This module already contains over 500 lines of code. If new features are added (and I hope so), it will become more and more difficult to keep track. It is also difficult to implement a new feature, because there are many dependencies.

**Proposal**
That's why I suggest we start splitting the code into two modules:

1. **Logic**: The main module where all the business logic is located. The data needed to generate the payment slip is stored here. Most of the current code will stay here.

2. **Render**: This module is responsible for generating an output file. At the beginning only SVG is supported. Other formats can be added as features. The code used to create the svg image will be moved here.

**Advantages**

- We achieve a separation of concern.
- We can test the logic and the render independently.
- The render can be exchanged without damaging the logic.
- Maintenance and further development is simplified, because the code as a whole becomes clearer.

I am happy to get your feedback and discuss other approaches 😃

**Comment by claudep** [comment]
I see your point. However, for me a module of 500 lines of code is not so big and still well manageable.
Secondly, I'm not sure we'll ever add other rendering outputs. I'd rather suggest piping our SVG result to other conversion tools. I'm not opposed to some changes, but I'd rather proceed with them when the need arises, instead of over-engineering this module for unsure scenarios.

**Comment by aloistr** [comment]
I tried to install on RHEL 7
This happens:
pip install qrbill
Collecting qrbill
  Using cached qrbill-0.5.tar.gz (13 kB)
  WARNING: Generating metadata for package qrbill produced metadata for project name unknown. Fix your #egg=qrbill fragments.
Using legacy setup.py install for unknown, since package 'wheel' is not installed.
Using legacy setup.py install for unknown, since package 'wheel' is not installed.
Installing collected packages: unknown
    Running setup.py install for unknown ... done
Successfully installed unknown-0.0.0

I get a package 'unknown' installed.

**Comment by claudep** [comment]
@aloistr Your comment has nothing to do with this issue, please avoid that in the future.

**Comment by aloistr** [comment]
Sorry for that.

I have not enough experience with github issues system. Should have 
opened a different issue. I deleted my comment.

Do you happen to know where can I find help to solve the pip install 
problem of your package?
I tried to follow your install instructions.

**Comment by claudep** [comment]
@aloistr Thanks for having removed your comment. Yes, you should open a new issue, however I guess you are facing #32.

**Comment by claudep** [comment]
I'm going to close this issue. Not that your idea has no merits, but the library has currently no plans to get many more functionalities, so the need for modularity is not obvious to me, at least for now.
